package testeMaven.model;
// Generated 2 de set. de 2025 18:34:22 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbanimal generated by hbm2java
 */
@Entity
@Table(name="tbanimal"
    ,catalog="bdpetshop"
)
public class Tbanimal  implements java.io.Serializable {


     private Integer id;
     private Tbcliente tbcliente;
     private String nome;
     private String raca;
     private Set<Tbservico> tbservicos = new HashSet<Tbservico>(0);

    public Tbanimal() {
    }

	
    public Tbanimal(Tbcliente tbcliente, String nome, String raca) {
        this.tbcliente = tbcliente;
        this.nome = nome;
        this.raca = raca;
    }
    public Tbanimal(Tbcliente tbcliente, String nome, String raca, Set<Tbservico> tbservicos) {
       this.tbcliente = tbcliente;
       this.nome = nome;
       this.raca = raca;
       this.tbservicos = tbservicos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codCliente", nullable=false)
    public Tbcliente getTbcliente() {
        return this.tbcliente;
    }
    
    public void setTbcliente(Tbcliente tbcliente) {
        this.tbcliente = tbcliente;
    }

    
    @Column(name="nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="raca", nullable=false)
    public String getRaca() {
        return this.raca;
    }
    
    public void setRaca(String raca) {
        this.raca = raca;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbanimal")
    public Set<Tbservico> getTbservicos() {
        return this.tbservicos;
    }
    
    public void setTbservicos(Set<Tbservico> tbservicos) {
        this.tbservicos = tbservicos;
    }




}


