package testeMaven.model;
// Generated 2 de set. de 2025 07:16:39 by Hibernate Tools 5.6.15.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tbservico generated by hbm2java
 */
@Entity
@Table(name="tbservico"
    ,catalog="bdpetshop"
)
public class Tbservico  implements java.io.Serializable {


     private int id;
     private Tbanimal tbanimal;
     private Tbcliente tbcliente;
     private String descricao;
     private double valor;
     private int formaPagamento;
     private boolean pago;

    public Tbservico() {
    }

    public Tbservico(int id, Tbanimal tbanimal, Tbcliente tbcliente, String descricao, double valor, int formaPagamento, boolean pago) {
       this.id = id;
       this.tbanimal = tbanimal;
       this.tbcliente = tbcliente;
       this.descricao = descricao;
       this.valor = valor;
       this.formaPagamento = formaPagamento;
       this.pago = pago;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codAnimal", nullable=false)
    public Tbanimal getTbanimal() {
        return this.tbanimal;
    }
    
    public void setTbanimal(Tbanimal tbanimal) {
        this.tbanimal = tbanimal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codCliente", nullable=false)
    public Tbcliente getTbcliente() {
        return this.tbcliente;
    }
    
    public void setTbcliente(Tbcliente tbcliente) {
        this.tbcliente = tbcliente;
    }

    
    @Column(name="descricao", nullable=false)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="valor", nullable=false, precision=22, scale=0)
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }

    
    @Column(name="formaPagamento", nullable=false)
    public int getFormaPagamento() {
        return this.formaPagamento;
    }
    
    public void setFormaPagamento(int formaPagamento) {
        this.formaPagamento = formaPagamento;
    }

    
    @Column(name="pago", nullable=false)
    public boolean isPago() {
        return this.pago;
    }
    
    public void setPago(boolean pago) {
        this.pago = pago;
    }




}


