package pizzaria.model;
// Generated 2 de set. de 2025 19:00:22 by Hibernate Tools 5.6.15.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PedidopizzaId generated by hbm2java
 */
@Embeddable
public class PedidopizzaId  implements java.io.Serializable {


     private int codpedido;
     private int codpizza;

    public PedidopizzaId() {
    }

    public PedidopizzaId(int codpedido, int codpizza) {
       this.codpedido = codpedido;
       this.codpizza = codpizza;
    }
   


    @Column(name="codpedido", nullable=false)
    public int getCodpedido() {
        return this.codpedido;
    }
    
    public void setCodpedido(int codpedido) {
        this.codpedido = codpedido;
    }


    @Column(name="codpizza", nullable=false)
    public int getCodpizza() {
        return this.codpizza;
    }
    
    public void setCodpizza(int codpizza) {
        this.codpizza = codpizza;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PedidopizzaId) ) return false;
		 PedidopizzaId castOther = ( PedidopizzaId ) other; 
         
		 return (this.getCodpedido()==castOther.getCodpedido())
 && (this.getCodpizza()==castOther.getCodpizza());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodpedido();
         result = 37 * result + this.getCodpizza();
         return result;
   }   


}


