package pizzaria.model;
// Generated 2 de set. de 2025 19:00:22 by Hibernate Tools 5.6.15.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pedidopizza generated by hbm2java
 */
@Entity
@Table(name="pedidopizza"
    ,catalog="bdpizzaria"
)
public class Pedidopizza  implements java.io.Serializable {


     private PedidopizzaId id;

    public Pedidopizza() {
    }

    public Pedidopizza(PedidopizzaId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codpedido", column=@Column(name="codpedido", nullable=false) ), 
        @AttributeOverride(name="codpizza", column=@Column(name="codpizza", nullable=false) ) } )
    public PedidopizzaId getId() {
        return this.id;
    }
    
    public void setId(PedidopizzaId id) {
        this.id = id;
    }




}


