package testeMaven.model;
// Generated 2 de set. de 2025 18:34:22 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbcliente generated by hbm2java
 */
@Entity
@Table(name="tbcliente"
    ,catalog="bdpetshop"
)
public class Tbcliente  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String cpf;
     private String telefone;
     private String email;
     private Set<Tbservico> tbservicos = new HashSet<Tbservico>(0);
     private Set<Tbanimal> tbanimals = new HashSet<Tbanimal>(0);

    public Tbcliente() {
    }

	
    public Tbcliente(String nome, String cpf, String telefone) {
        this.nome = nome;
        this.cpf = cpf;
        this.telefone = telefone;
    }
    public Tbcliente(String nome, String cpf, String telefone, String email, Set<Tbservico> tbservicos, Set<Tbanimal> tbanimals) {
       this.nome = nome;
       this.cpf = cpf;
       this.telefone = telefone;
       this.email = email;
       this.tbservicos = tbservicos;
       this.tbanimals = tbanimals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="CPF", nullable=false, length=15)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="Telefone", nullable=false, length=15)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="Email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbcliente")
    public Set<Tbservico> getTbservicos() {
        return this.tbservicos;
    }
    
    public void setTbservicos(Set<Tbservico> tbservicos) {
        this.tbservicos = tbservicos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbcliente")
    public Set<Tbanimal> getTbanimals() {
        return this.tbanimals;
    }
    
    public void setTbanimals(Set<Tbanimal> tbanimals) {
        this.tbanimals = tbanimals;
    }




}


