/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a02ex06;

import javax.swing.JOptionPane;

/**
 *
 * @author ALUNO
 */
public class A02ex05 extends javax.swing.JFrame {

    /**
     * Creates new form exercicio
     */
    public A02ex05() {
        initComponents();
    }

    private int acertos = 0, erros = 0, posicao;
    private void atualizarAcertos(){
        acertos++;
        String resultado = "" + acertos;
        for(int i = resultado.length(); resultado.length() < 3; i++){
            System.out.println("Entrou");
            String aux = resultado;
            resultado = "";
            resultado += "0";
            resultado += aux;
        }
        lblPontuacaoAcertos.setText("" + resultado);
    }
    private void atualizarErros(){
        erros++;
        String resultado = "" + erros;
        for(int i = resultado.length(); resultado.length() < 3; i++){
            System.out.println("Entrou");
            String aux = resultado;
            resultado = "";
            resultado += "0";
            resultado += aux;
        }
        lblPontuacaoErros.setText("" + resultado);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPontuacao = new javax.swing.JLabel();
        lblPontuacaoAcertos = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        lblPontuacaoErros = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        btnResposta1 = new javax.swing.JButton();
        btnResposta3 = new javax.swing.JButton();
        btnResposta2 = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblValorStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblPontuacao.setText("Pontuação:");

        lblPontuacaoAcertos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPontuacaoAcertos.setForeground(new java.awt.Color(0, 0, 204));
        lblPontuacaoAcertos.setText("000");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        lblPontuacaoErros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPontuacaoErros.setForeground(new java.awt.Color(255, 204, 102));
        lblPontuacaoErros.setText("000");

        lblValor1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblValor1.setText("0");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("+");

        lblValor2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblValor2.setText("0");

        btnResposta1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnResposta1.setText("0");
        btnResposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResposta1ActionPerformed(evt);
            }
        });

        btnResposta3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnResposta3.setText("0");
        btnResposta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResposta3ActionPerformed(evt);
            }
        });

        btnResposta2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnResposta2.setText("0");
        btnResposta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResposta2ActionPerformed(evt);
            }
        });

        lblStatus.setText("Status:");

        lblValorStatus.setText("escolha a resposta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPontuacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPontuacaoAcertos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPontuacaoErros)
                        .addGap(55, 55, 55)
                        .addComponent(btnNovo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnResposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValor1)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblValor2)
                        .addGap(69, 69, 69)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValorStatus)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPontuacao)
                    .addComponent(lblPontuacaoAcertos)
                    .addComponent(btnNovo)
                    .addComponent(lblPontuacaoErros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValor1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(lblValorStatus))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        int valor1 = (int) (Math.random() * 10);
        int valor2 = (int) (Math.random() * 10);
        
        lblValor1.setText("" + valor1);
        lblValor2.setText("" + valor2);
        
        int respostaCerta = valor1 + valor2;
        
        posicao = (int) (Math.random() * 10) % 3;
        
        int respostaErrada1 = (int) (Math.random() * 10);
        while(respostaErrada1 == respostaCerta){
            respostaErrada1 = (int) (Math.random() * 10);
        }
    
        int respostaErrada2 = (int) (Math.random() * 10);
        while(respostaErrada2 == respostaCerta && respostaErrada2 == respostaErrada1){
            respostaErrada2 = (int) (Math.random() * 10);
        }
        switch (posicao) {
            case 0: btnResposta1.setText("" + respostaCerta);
                    btnResposta2.setText("" + respostaErrada1);
                    btnResposta3.setText("" + respostaErrada2);
                    break;
            case 1: btnResposta1.setText("" + respostaErrada1);
                    btnResposta2.setText("" + respostaCerta);
                    btnResposta3.setText("" + respostaErrada2);
                    break;
            case 2: btnResposta1.setText("" + respostaErrada1);
                    btnResposta2.setText("" + respostaErrada2);
                    btnResposta3.setText("" + respostaCerta);
                    break;
            default: JOptionPane.showMessageDialog(null, "Houve um erro ao gerar um novo jogo, por favor, clique novamente no botão 'Novo'");
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnResposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResposta1ActionPerformed
        // TODO add your handling code here:
        if(posicao == 0){
            lblValorStatus.setText("Você acertou");
            atualizarAcertos();
        }
        else{
            lblValorStatus.setText("Você errou");
            atualizarErros();
        }
    }//GEN-LAST:event_btnResposta1ActionPerformed

    private void btnResposta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResposta3ActionPerformed
        // TODO add your handling code here:
        if(posicao == 2){
            lblValorStatus.setText("Você acertou");
            atualizarAcertos();
        }
        else{
            lblValorStatus.setText("Você errou");
            atualizarErros();
        }
    }//GEN-LAST:event_btnResposta3ActionPerformed

    private void btnResposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResposta2ActionPerformed
        // TODO add your handling code here:
        if(posicao == 1){
            lblValorStatus.setText("Você acertou");
            atualizarAcertos();
        }
        else{
            lblValorStatus.setText("Você errou");
            atualizarErros();
        }
    }//GEN-LAST:event_btnResposta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A02ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A02ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A02ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A02ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A02ex05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnResposta1;
    private javax.swing.JButton btnResposta2;
    private javax.swing.JButton btnResposta3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPontuacao;
    private javax.swing.JLabel lblPontuacaoAcertos;
    private javax.swing.JLabel lblPontuacaoErros;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JLabel lblValorStatus;
    // End of variables declaration//GEN-END:variables
}
