/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package testeMaven.view;

import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import testeMaven.controller.AnimaisController;
import testeMaven.controller.ClientesController;
import testeMaven.model.Tbanimal;
import testeMaven.model.Tbcliente;

/**
 *
 * @author bruno
 */
public class EditarAnimalView extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarAnimalView.class.getName());

    private int idClasse;
    private Tbcliente clienteSelecionado;
    private List<Tbcliente> clientes;
    private Tbanimal animal;
    /**
     * Creates new form EditarCliente
     */
    public EditarAnimalView(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        idClasse = id;
        initComponents();
        
        animal = new AnimaisController().buscarPorId(id);
        clientes = new ClientesController().listarTodos();
        
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<String>();
        for (Tbcliente cliente : clientes) {
            comboBoxModel.addElement(cliente.getCpf());
        }
        cmbDono.setModel(comboBoxModel);
        
        lblNomeAnimal.setText(animal.getNome());
        txtNome.setText(animal.getNome());
        txtRaca.setText(animal.getRaca());
        txtNomeDono.setText(animal.getTbcliente().getNome());
        cmbDono.setSelectedItem(animal.getTbcliente().getCpf());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        txtRaca = new javax.swing.JTextField();
        lblEditar = new javax.swing.JLabel();
        txtNomeDono = new javax.swing.JTextField();
        lblNomeAnimal = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblRaca = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblNomeDono = new javax.swing.JLabel();
        lblCpfDono = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cmbDono = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtRaca.setText("Raça");

        lblEditar.setText("Editar Animal");

        txtNomeDono.setText("Nome do Dono");

        lblNomeAnimal.setText("Nome do Animal");

        lblNome.setText("Nome do animal");

        lblRaca.setText("Raça");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblNomeDono.setText("Nome do Dono");

        lblCpfDono.setText("CPF do Dono");

        txtNome.setText("Nome");

        cmbDono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        cmbDono.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDonoItemStateChanged(evt);
            }
        });
        cmbDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeAnimal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblRaca)
                                    .addComponent(lblNomeDono)
                                    .addComponent(lblCpfDono))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtNome)
                                    .addComponent(txtRaca)
                                    .addComponent(txtNomeDono)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditar)
                    .addComponent(lblNomeAnimal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaca)
                    .addComponent(txtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblCpfDono)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeDono)
                            .addComponent(txtNomeDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnSalvar))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        int resultado = JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar as alterações sem salvar?", "Cancelar?", 0);
        if(resultado == 0){
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String alteracoes = "Deseja realmente SALVAR as alterações?";
        alteracoes += "\n\nNome: " + txtNome.getText();
        alteracoes += "\nRaça: " + txtRaca.getText();
        alteracoes += "\nNome do Dono: " + txtNomeDono.getText();
        alteracoes += "\nCPF: " + cmbDono.getSelectedItem();

        int resultado = JOptionPane.showConfirmDialog(null, alteracoes, "Salvar?", 0);
        if(resultado == 0){
            try {
                Tbanimal animal = new Tbanimal();
                animal.setId(idClasse);
                animal.setNome(txtNome.getText());
                animal.setRaca(txtRaca.getText());
                animal.setTbcliente(clienteSelecionado);
                new AnimaisController().salvar(animal);

                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
                this.dispose();
            }
            catch (Error e) {
                JOptionPane.showMessageDialog(null, "Houve um erro ao tentar salvar as alterações!\nPor favor, tente novamente!");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cmbDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDonoActionPerformed

    private void cmbDonoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDonoItemStateChanged
        // TODO add your handling code here:
        for(Tbcliente cliente : clientes ){
            if(evt.getItem().toString() == cliente.getCpf()){
                clienteSelecionado = cliente;
                txtNomeDono.setText(cliente.getNome());
            }
        }
    }//GEN-LAST:event_cmbDonoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditarAnimalView dialog = new EditarAnimalView(new javax.swing.JFrame(), true, -1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbDono;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblCpfDono;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeAnimal;
    private javax.swing.JLabel lblNomeDono;
    private javax.swing.JLabel lblRaca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeDono;
    private javax.swing.JTextField txtRaca;
    // End of variables declaration//GEN-END:variables
}
