/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pizzaria.view;

import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import pizzaria.controller.PedidosController;
import pizzaria.controller.ClientesController;
import pizzaria.model.Pedido;
import pizzaria.model.Clientes;
import pizzaria.model.Usuarios;

/**
 *
 * @author bruno
 */
public class EditarPedidosView extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarPedidosView.class.getName());

    private int idClasse;
    private Clientes clienteSelecionado;
    private List<Clientes> clientes;
    private Usuarios usuarioSelecionado;
    private List<Usuarios> usuarios;
    private Pedido pedido;
    /**
     * Creates new form EditarCliente
     */
    public EditarPedidosView(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        idClasse = id;
        initComponents();
        
        //pedido = new PedController().buscarPorId(id);
        clientes = new ClientesController().listarTodos();
        
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<String>();
        for (Clientes cliente : clientes) {
            comboBoxModel.addElement(cliente.getCpf());
        }
        cmbCpfCliente.setModel(comboBoxModel);
        
        lblNomeClienteTitulo.setText(pedido.getClientes().getNome());
        txtNomeCliente.setText(pedido.getClientes().getNome());
        txtNomeUsuario.setText(pedido.getUsuarios().getNome());
        cmbCpfCliente.setSelectedItem(pedido.getClientes().getCpf());
        cmbCpfUsuario.setSelectedItem(pedido.getUsuarios().getCpf());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        txtNomeUsuario = new javax.swing.JTextField();
        lblEditar = new javax.swing.JLabel();
        lblNomeClienteTitulo = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        lblRaca = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblCpfCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        cmbCpfCliente = new javax.swing.JComboBox<>();
        lblCpfUsuario = new javax.swing.JLabel();
        cmbCpfUsuario = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNomeUsuario.setEditable(false);
        txtNomeUsuario.setText("Nome do Usuário");

        lblEditar.setText("Editar Pedido do cliente:");

        lblNomeClienteTitulo.setText("Nome do Cliente");

        lblNomeCliente.setText("Nome do Cliente");

        lblRaca.setText("Nome do Usuário");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblCpfCliente.setText("CPF do Cliente");

        txtNomeCliente.setEditable(false);
        txtNomeCliente.setText("Nome do Cliente");

        cmbCpfCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        cmbCpfCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCpfClienteItemStateChanged(evt);
            }
        });
        cmbCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCpfClienteActionPerformed(evt);
            }
        });

        lblCpfUsuario.setText("CPF do Usuario");

        cmbCpfUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        cmbCpfUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCpfUsuarioItemStateChanged(evt);
            }
        });
        cmbCpfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCpfUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeClienteTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeCliente)
                                    .addComponent(lblCpfCliente))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtNomeCliente)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRaca)
                                    .addComponent(lblCpfUsuario))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbCpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtNomeUsuario))))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditar)
                    .addComponent(lblNomeClienteTitulo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCliente)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCliente)
                    .addComponent(cmbCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaca)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfUsuario)
                    .addComponent(cmbCpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        int resultado = JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar as alterações sem salvar?", "Cancelar?", 0);
        if(resultado == 0){
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String alteracoes = "Deseja realmente SALVAR as alterações?";
        alteracoes += "\n\nNome do Cliente: " + txtNomeCliente.getText();
        alteracoes += "\ncom CPF: " + cmbCpfCliente.getSelectedItem().toString();
        alteracoes += "\n\nNome do Usuário: " + txtNomeUsuario.getText();
        alteracoes += "\ncom CPF: " + cmbCpfUsuario.getSelectedItem().toString();

        int resultado = JOptionPane.showConfirmDialog(null, alteracoes, "Salvar?", 0);
        if(resultado == 0){
            try {
                Pedido pedido = new Pedido();
                pedido.setId(idClasse);
                pedido.setClientes(clienteSelecionado);
                pedido.setUsuarios(usuarioSelecionado);
                new PedidosController().salvar(pedido);

                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
                this.dispose();
            }
            catch (Error e) {
                JOptionPane.showMessageDialog(null, "Houve um erro ao tentar salvar as alterações!\nPor favor, tente novamente!");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cmbCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCpfClienteActionPerformed

    private void cmbCpfClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCpfClienteItemStateChanged
        // TODO add your handling code here:
        for(Clientes cliente : clientes ){
            if(evt.getItem().toString() == cliente.getCpf()){
                clienteSelecionado = cliente;
                txtNomeCliente.setText(cliente.getNome());
            }
        }
    }//GEN-LAST:event_cmbCpfClienteItemStateChanged

    private void cmbCpfUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCpfUsuarioItemStateChanged
        // TODO add your handling code here:
        for(Usuarios usuario : usuarios ){
            if(evt.getItem().toString() == usuario.getCpf()){
                usuarioSelecionado = usuario;
                txtNomeUsuario.setText(usuario.getNome());
            }
        }
    }//GEN-LAST:event_cmbCpfUsuarioItemStateChanged

    private void cmbCpfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCpfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCpfUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditarPedidosView dialog = new EditarPedidosView(new javax.swing.JFrame(), true, -1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCpfCliente;
    private javax.swing.JComboBox<String> cmbCpfUsuario;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblCpfUsuario;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeClienteTitulo;
    private javax.swing.JLabel lblRaca;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
