package pizzaria.model;
// Generated 2 de set. de 2025 22:09:16 by Hibernate Tools 5.6.15.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ingredientes generated by hbm2java
 */
@Entity
@Table(name="ingredientes"
    ,catalog="bdpizzaria"
)
public class Ingredientes  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private int quantidadeEstoque;

    public Ingredientes() {
    }

    public Ingredientes(String nome, int quantidadeEstoque) {
       this.nome = nome;
       this.quantidadeEstoque = quantidadeEstoque;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="QuantidadeEstoque", nullable=false)
    public int getQuantidadeEstoque() {
        return this.quantidadeEstoque;
    }
    
    public void setQuantidadeEstoque(int quantidadeEstoque) {
        this.quantidadeEstoque = quantidadeEstoque;
    }




}


