package pizzaria.model;
// Generated 2 de set. de 2025 22:09:16 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name="pedido"
    ,catalog="bdpizzaria"
)
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private Clientes clientes;
     private Usuarios usuarios;
     private Set<Pizza> pizzas = new HashSet<Pizza>(0);

    public Pedido() {
    }

	
    public Pedido(Clientes clientes, Usuarios usuarios) {
        this.clientes = clientes;
        this.usuarios = usuarios;
    }
    public Pedido(Clientes clientes, Usuarios usuarios, Set<Pizza> pizzas) {
       this.clientes = clientes;
       this.usuarios = usuarios;
       this.pizzas = pizzas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codCliente", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codUsuario", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="pedidopizza", catalog="bdpizzaria", joinColumns = { 
        @JoinColumn(name="codpedido", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="codpizza", nullable=false, updatable=false) })
    public Set<Pizza> getPizzas() {
        return this.pizzas;
    }
    
    public void setPizzas(Set<Pizza> pizzas) {
        this.pizzas = pizzas;
    }




}


