package pizzaria.model;
// Generated 2 de set. de 2025 22:09:16 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Pizza generated by hbm2java
 */
@Entity
@Table(name="pizza"
    ,catalog="bdpizzaria"
)
public class Pizza  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private double valor;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Pizza() {
    }

	
    public Pizza(String nome, double valor) {
        this.nome = nome;
        this.valor = valor;
    }
    public Pizza(String nome, double valor, Set<Pedido> pedidos) {
       this.nome = nome;
       this.valor = valor;
       this.pedidos = pedidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="Valor", nullable=false, precision=22, scale=0)
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="pedidopizza", catalog="bdpizzaria", joinColumns = { 
        @JoinColumn(name="codpizza", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="codpedido", nullable=false, updatable=false) })
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


